name: Update-infrastructure-backend

on: 
  workflow_dispatch:
    inputs:
      sha-tag:
        description: 'sha tag for new image'     
        required: true
      code-branch:
        description: 'branch of code repository'
        required: true
      overlays-dir:
        description: 'kustomize directory'
        required: true

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      
      
      - name: Checkout code repo
        uses: actions/checkout@v2
        with:
            repository: mattedamo/thesis-microservices-app-backend-first-attempt
            token: ${{secrets.WORKFLOW_DISPATCH}}
            ref: ${{ github.event.inputs.code-branch }}
            path: code-repo
      - run: cp code-repo/file.yaml ./file.yaml
      
      - name: Setup Python
        uses: actions/setup-python@v2
        with: 
          python-version: "3.x"

      - run: pip install PyYAML
        name: Install py dependencies
      - run: python final-script.py
        name: Run python script, update kustomize overlays
      

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with: 
          kustomize-version: "3.6.1"
     
      - name: Update Kubernetes Image
        env: 
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd kustomize/overlays/${{ github.event.inputs.overlays-dir }}
          kustomize edit set image frontend=$DOCKER_USERNAME/first-attempt-backend:${{ github.event.inputs.sha-tag }}
          
      - run: rm -f file.yaml
      - run: rm -rf code-repo/
       
      - name: Commit files
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -am "Bump kustomize files"
       
      - name: Push changes
        uses: ad-m/github-push-action@master
        with: 
          github_token: ${{ secrets.GITHUB_TOKEN }}
