apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: database-deployment
  name: database-deployment
spec:
  selector:
    matchLabels:
      app: database-pod
  template:
    metadata:
      labels:
        app: database-pod
    spec:
      containers:
      - name: mariadb
        env: 
        - name: "DB_PASSWORD"
          valueFrom:
            secretKeyRef:
              name: db-config
              key:  MYSQL_ROOT_PASSWORD
        - name: "DB_NAME"
          valueFrom:
            secretKeyRef:
              name: db-config
              key:  MYSQL_DATABASE
