apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: databse-deployment
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb:latest
          name: mariadb
          ports:
            - name: http
              containerPort: 3306
