apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mariadb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mariadb
  replicas: 1
  template:
    metadata:
      labels:
        app: mariadb
    spec:
      containers:
        - image: mariadb:latest
          name: mariadb
          ports:
            - name: http
              containerPort: 3306
