apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend-deployment
  name: backend-deployment
  namespace: thesis-microservices-app-first-attempt
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-pod
  template:
    metadata:
      labels:
        app: backend-pod
    spec:
      containers:
        - image: first-attempt-backend 
          name: backend
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080

