resources: 
- deployment-backend.yaml 
- deployment-database.yaml
- secret-mariadb.yaml
- service-backend.yaml
- service-database.yaml
- namespace.yaml
namespace: thesis-microservices-app-first-attempt
images:
  - name: backend
    newName: mattedamo26/first-attempot-backend
    newTag: latest
