apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-backend.yaml
- deployment-database.yaml
- service-backend.yaml
- service-database.yaml
- deployment-frontend.yaml
- service-frontend.yaml
namespace: thesis-microservices-app-first-attempt
images:
- name: backend
  newName: mattedamo26/first-attempt-backend
  newTag: 3b357dca738a297993a9c46792c1caf9cc1ccbd5
- name: frontend
  newName: mattedamo26/first-attempt-frontend
  newTag: AAAAAAAAAAAAAAAAA
