apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-backend.yaml
- deployment-database.yaml
- service-backend.yaml
- service-database.yaml
namespace: thesis-microservices-app-first-attempt
images:
- name: backend
  newName: mattedamo26/first-attempt-backend
  newTag: ce7c4d1fa9b7eefa73cf08ff212a89f630c3c275
- name: frontend
  newName: mattedamo26/first-attempt-frontend
  newTag: e3d82b4ab986fcee4fe1825e0c8d14b2c7b33041
