apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-backend.yaml
- deployment-database.yaml
- service-backend.yaml
- service-database.yaml
namespace: thesis-microservices-app-first-attempt
images:
- name: backend
  newName: mattedamo26/first-attempt-backend
  newTag: c9c40b12f6086350d034cc4a6261e1c5db441672
- name: frontend
  newName: mattedamo26/first-attempt-frontend
  newTag: e3d82b4ab986fcee4fe1825e0c8d14b2c7b33041
