apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment-backend.yaml
- deployment-database.yaml
- service-backend.yaml
- service-database.yaml
- namespace.yaml
namespace: thesis-microservices-app-first-attempt

