apiVersion: v1
kind: Secret
metadata:
  name: secret-mariadb
  namespace: thesis-microservices-app-first-attempt
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cGFzc3dvcmQ=
  MYSQL_DATABASE: dGhlc2lzQXBwTWFyaWFkYg==

