apiVersion: v1
kind: Service
metadata: 
  name: backend-service
  name: thesis-microservices-app-first-attempt
  labels:
    app: backend-service
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: backend-pod
